### ISSUE TITLE
Bug - Aktualisieren von Content scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by Dalanie** [Integreat/app#95]
Konnte ich gerade sogar reproduzieren: Hatte Main-Taunus-Kreis vor wenigen Tagen geladen, und scheinbar viele Seiten aus der globalen Instanz / Deutschland-Instanz. 

Nach Textänderung in oeffentliche-verkehrsmittel/ wurde diese jedoch nicht in der App angezeigt - auch nicht nach "force"-refresh. Erst nach Daten löschen und gesamtes neuladen hat die Änderung bewirkt.

Ich vermute wir haben nen modification-date Problem mit Deutschland-Instanz/Stadt-Instanz.

**Comment by Meash** [comment]
Sehr dringend, App wird beim mtk gerade kommuniziert

**Comment by Dalanie** [comment]
Kann irgendjemand diesen Fehler reproduzieren? Ich habe aus Zufall den Fehler gesehen, aber seitdem nicht reproduzieren können. Ich habe einen Fehler, der in dieser Richtung lag, behoben (Update-Datum schlägt fehl). Meiner Meinung nach, sollte dies aber nicht das Problem gewesen sein..

**Comment by Dalanie** [comment]
@matsair @ammyg  - Habt ihr Ideen, woran es liegen könnte? Die Modification-Dates sind scheinbar korrekt gesetzt und die "neueren" Artikel haben dementsprechend ein älteres Datum als die Artikel aus der Deutschland-Instanz

**Comment by ammyg** [comment]
Also in der App konnte ich auch nichts finden.

Ich bin aber im CMS über etwas gestolpert (Ich hab mit WP noch nicht so arg viel gearbeitet, evtl kann das mal einer beurteilen, der sich damit auskennt):

Wir geben ja durch den Parameter "since" einen Zeitstempel an, ab dem wir alle Änderungen haben wollen. So wie ich den PHP-Code von unserer Rest-API verstanden habe, werden alle Seiten zurück gegeben, deren post_modified_gmt >= diesem Zeitstempel ist. Ich hab jetzt auf einer Test-WP-Instanz ein paar Tests gemacht. Wenn ich eine Veröffentlichung "plane", dann ist post_modified_gmt der Zeitpunkt der Speicherung und nicht der Veröffentlichung. Über die Rest-API ist die Seite aber erst ab dem Zeitpunkt der Veröffentlichung abrufbar. Wenn jetzt ein Client zwischen Speicherung und Veröffentlichung des Artikels die Seiten abruft/neu lädt (und dabei mindestens eine Seite drin ist, deren post_modified_gmt größer als der entsprechende der noch nicht veröffentlichten Seite ist), dann bekommt die App die Änderung nach Veröffentlichung nicht mehr mit. Bei uns tritt das wahrscheinlich vor allem dann auf, wenn eine Organisation einen Text erstellt, der später vom Verwalter der Instanz (ohne weitere Bearbeitung) freigeschaltet wird.

Auf Anhieb würde ich Vorschlagen, anstatt post_modified_gmt einfach post_date_gmt (im CMS-Plug-in) nehmen. Das müsste der Zeitpunkt der Veröffentlichung sein.

@Meash Könnte es daran liegen?

**Comment by Meash** [comment]
Super Beobachtung, das könnte es sein.
Ändere ich später gleich

**Comment by Dalanie** [comment]
Woah, Respekt für den Fund!

**Comment by Dalanie** [comment]
@Meash  Meinst das Problem liegt im CMS? Kann ich das Ticket erstmal schließen?

**Comment by Meash** [comment]
Wir haben außer den geplanten Inhalten nichts gefunden, lass uns erstmal
die Antwort abwarten von dem, der die Inhalte eingegeben hat.

**Comment by Meash** [comment]
Konnten etwas reproduzieren:
Unter `http://vmkrcmar21.informatik.tu-muenchen.de/wordpress/main-taunus-kreis/de/wp-json/extensions/v0/modified_content/pages?since=2015-11-20T00:00:00Z` kommt u.a. ein Update der Seite mit ID 41 zurück. In der App wird allerdings auch nach forciertem Update (Runterziehen) noch der alte Inhalt dieser Seite angezeigt.

**Comment by ammyg** [comment]
Ich glaube, dass ich den Fehler gefunden habe. Er liegt im PageSerializer in der Methode parsePages(@NonNull final JsonArray jsonPages):

parsePages sucht sich zunächst alle root-Pages um dann zu jeder root-Page die sub-pages zu suchen. Wenn sich jetzt allerdings nur eine Subpage aktualisiert, dann ist die Liste der root-Pages leer und somit beendet er die Methode sofort.

**Comment by Dalanie** [comment]
Ich hab den Quellcode gerade vor mir, kann es aber nicht testen. Aber ja, du hast Recht! Ich bin mir gerade nicht einmal sicher, wieso wir ueberhaupt die root-pages zurueckgeben und nicht einfach alle Pages. Da gab es irgendwas, glaube es hat mit den Referenzen zu tun, die wir dort eventuell aufbauen - vllt muessten wir mal nachschauen warum das ganze benoetigt wurde und ob es noch notwendig ist.

**Comment by Dalanie** [comment]
Sehr gutes Auge!

**Comment by Dalanie** [comment]
der Parser wird ja nur fuer PageResource verwendet, afaik. PageResource laedt die Daten und ruft dann store(..) auf. In Store trennen wir wieder die Hierarchy und speichern Page fuer Page in die db. Vielleicht koennen wir also einfach jede Page parsen und keine Hierarchie aufbauen

**Comment by ammyg** [comment]
Ich hab es getestet: Bei mir hat er jetzt die Seite aktualisiert. Alles andere scheint auch noch zu funktionieren.

**Comment by Dalanie** [comment]
Sehr gut!

**Comment by Meash** [comment]
Gute Arbeit, so schnelles Bug fixing ist mal erfrischend ;)
Am 20.11.2015 21:01 schrieb "Daniel Langerenken" <notifications@github.com>:
